src/objects/Food_Bank_Box_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>List of family-size thresholds for different food bank bag or box types. Names should match drop-down list in Visit object.</description>
    <fields>
        <fullName>Minimum_Family_Size__c</fullName>
        <label>Minimum Family Size</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Food Bank Bag/Box Settings</label>
</CustomObject>

src/objects/Food_Bank_Commodity__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>List of items for which the food bank tracks monthly limits and usage - for example, you get up to 3 boxes of eggs per month.</description>
    <fields>
        <fullName>Allow_Overage__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, staff will be alerted when clients use more than the limit, but can choose to overlook the warning.</inlineHelpText>
        <label>Allow Overage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Monthly_Limit__c</fullName>
        <label>Monthly Limit</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Food Bank Commodity</label>
</CustomObject>

src/objects/Food_Bank_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>General settings for food bank application</description>
    <fields>
        <fullName>Allow_Box_Size_Override__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, staff has the option to specify the box size to provide, overriding the default for the family size.</inlineHelpText>
        <label>Allow Bag/Box Size Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Allow_Overage__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, staff can override the alert that monthly point or visit limits have been exceeded.</inlineHelpText>
        <label>Allow Overage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Check_in_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box if your food bank requires clients to check in before shopping and check out afterward</inlineHelpText>
        <label>Check-in Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Monthly_Base_Points__c</fullName>
        <inlineHelpText>Number of monthly points for a one-person household.  Leave blank if you do not limit points.</inlineHelpText>
        <label>Monthly Base Points</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_Points_Per_Adult__c</fullName>
        <inlineHelpText>Additional monthly points per adult over one.</inlineHelpText>
        <label>Monthly Points Per Adult</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_Points_Per_Child__c</fullName>
        <inlineHelpText>Additional monthly points per child in household.</inlineHelpText>
        <label>Monthly Points Per Child</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Proof_of_Address_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this to require proof of address for new client households.</inlineHelpText>
        <label>Proof of Address Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Proof_of_Address_Update_Interval__c</fullName>
        <inlineHelpText>Number of months after which updated proof of address is required for existing households.</inlineHelpText>
        <label>Proof of Address Update Interval</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Proof_of_Infant_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Proof of Infant Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Require_Unique_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box to prevent users from adding duplicate addresses.  If unchecked, users are still alerted when entering a duplicate, but can choose to continue.</inlineHelpText>
        <label>Require Unique Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tags__c</fullName>
        <description>Semi-colon delimited list of tags for client households.</description>
        <inlineHelpText>Semi-colon delimited list of tags for client households. Example:  Special Diet; Spanish Speaker</inlineHelpText>
        <label>Tags</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Track_Points__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box if you track monthly points. If unchecked, application will track bag/box size instead.</inlineHelpText>
        <label>Track Points</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Welcome_Alert__c</fullName>
        <inlineHelpText>Optional alert that will be shown prominently on Food Bank intake tab.</inlineHelpText>
        <label>Welcome Alert</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Welcome_Message__c</fullName>
        <inlineHelpText>Shown at top of Food Bank intake tab</inlineHelpText>
        <label>Welcome Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Food Bank Settings</label>
</CustomObject>

src/classes/FoodBankSettings.cls
public with sharing class FoodBankSettings {

    /**************************************************************************
    * The pattern is to create a static property for each settings object
    * and provide defaults if it is a test. Each setting will be instantiated
    * only once per transaction.
    *
    * To refer to a setting in the first section below, use:
    *   FoodBankSettings.general.Monthly_Visit_Limit__c
    *
    * For a list setting, specify the value you want:
    *   FoodBankSettings.commodity('Bread').Monthly_Limit__c
    *
    ***************************************************************************/

    public static Food_Bank_Settings__c general {
        get {
            if (general == null) {
                general = Food_Bank_Settings__c.getOrgDefaults();
                if (Test.isRunningTest()) {
                    // defaults for testing
                    general.Allow_Box_Size_Override__c = false;
                    general.Allow_Overage__c = false;
                    general.Monthly_Base_Points__c = 30;
                    general.Monthly_Points_Per_Adult__c = 10;
                    general.Monthly_Points_Per_Child__c = 10;
                    general.Check_in_Required__c = false;
                    general.Proof_of_Address_Required__c = true;
                    general.Proof_of_Address_Update_Interval__c = 12;
                    general.Require_Unique_Address__c = false;
                    general.Proof_of_Infant_Required__c = true;
                    general.Track_Points__c = true;
                    general.Tags__c = 'Special Diet; Spanish Speaker';
                    general.Welcome_Alert__c = 'Hello!';
                    general.Welcome_Message__c = 'Welcome to the food bank.';
                }
            }
            return general;
        }
        set;
    }

    public static list<Food_Bank_Commodity__c> commodities {
        get {
            if (commodities == null) {
                commodities = (!Test.isRunningTest()) ?
                    [select name, Monthly_Limit__c, Allow_Overage__c from Food_Bank_Commodity__c order by Sort_Order__c, name] :
                    new List<Food_Bank_Commodity__c>{
                        new Food_Bank_Commodity__c(
                            Name = 'Meat',
                            Monthly_Limit__c = 5,
                            Sort_Order__c = 0,
                            Allow_Overage__c = false ),
                        new Food_Bank_Commodity__c(
                            Name = 'Bread',
                            Monthly_Limit__c = 3,
                            Sort_Order__c = 1,
                            Allow_Overage__c = true )
                    };
            }
            return commodities;
        }
        set;
    }

    public static list<Food_Bank_Box_Settings__c> boxes {
        get {
            if (boxes == null) {
                boxes = (!Test.isRunningTest()) ?
                    [select name, Minimum_Family_Size__c from Food_Bank_Box_Settings__c order by Minimum_Family_Size__c asc nulls last, name] :
                    new List<Food_Bank_Box_Settings__c>{
                        new Food_Bank_Box_Settings__c(
                            Name = 'Small',
                            Minimum_Family_Size__c = 1 ),
                        new Food_Bank_Box_Settings__c(
                            Name = 'Large',
                            Minimum_Family_Size__c = 3 ),
                        new Food_Bank_Box_Settings__c(
                            Name = 'No Cook' )
                    };
            }
            return boxes;
        }
        set;
    }
}